version: '3'

services:
  eve_srp_db:
    container_name: eve_srp_db
    image: mariadb:10.6
    volumes: ["./.db/mariadb:/var/lib/mysql"]
    environment:
      MYSQL_ROOT_PASSWORD: eve_srp
      MYSQL_USER: eve_srp
      MYSQL_PASSWORD: eve_srp
      MYSQL_DATABASE: eve_srp
    ports: ["33061:3306"]
    networks: [eve-srp]

  eve_srp_db_postgres:
    container_name: eve_srp_db_postgres
    image: postgres:13-alpine
    volumes: ["./.db/postgresql:/var/lib/postgresql/data"]
    environment:
      POSTGRES_PASSWORD: eve_srp
    ports: ["55432:5432"]
    networks: [eve-srp]

  eve_srp_node:
    container_name: eve_srp_node
    image: node:20.14.0-alpine
    tty: true
    volumes: [".:/app"]
    working_dir: /app

  eve_srp_php:
    container_name: eve_srp_php
    build:
      context: config
      #dockerfile: dockerfile-php81-fpm
      #dockerfile: dockerfile-php82-fpm
      dockerfile: dockerfile-php83-fpm
    depends_on: [eve_srp_db]
    volumes: [".:/app"]
    working_dir: /app
    networks: [eve-srp]
    dns: [8.8.8.8]

  eve_srp_http:
    container_name: eve_srp_http
    image: nginx:1
    depends_on: [eve_srp_php]
    volumes: [".:/app", "./config/docker-nginx.conf:/etc/nginx/conf.d/default.conf"]
    ports: ["8000:80"]
    networks: [eve-srp]

networks:
  eve-srp:
    #external:
      #name: neucore_dev
      #name: neucore_prod
