version: '3'

services:
  eve_srp_db:
    container_name: eve_srp_db
    image: mariadb:10.4
    volumes: ["./.mariadb:/var/lib/mysql"]
    environment:
      MYSQL_ROOT_PASSWORD: eve_srp
      MYSQL_USER: eve_srp
      MYSQL_PASSWORD: eve_srp
      MYSQL_DATABASE: eve_srp
    networks: [eve-srp]

  eve_srp_node:
    container_name: eve_srp_node
    image: node:14.17-alpine
    volumes: [".:/app"]
    working_dir: /app

  eve_srp_php:
    container_name: eve_srp_php
    build:
      context: config
      dockerfile: dockerfile-php74-fpm
      #dockerfile: dockerfile-php80-fpm
    depends_on: [eve_srp_db]
    volumes: [".:/app"]
    working_dir: /app
    networks: [eve-srp]

  eve_srp_http:
    container_name: eve_srp_http
    image: nginx:1
    depends_on: [eve_srp_php]
    volumes: [".:/app", "./config/docker-nginx.conf:/etc/nginx/conf.d/default.conf"]
    ports: ["8000:80"]
    networks: [eve-srp]

networks:
  eve-srp:
    #external:
      #name: neucore_dev
      #name: neucore_prod
