version: '3'

services:
  db:
    container_name: eve_srp_db
    image: mariadb:10.4
    volumes: ["./.mariadb:/var/lib/mysql"]
    environment:
      MYSQL_ROOT_PASSWORD: eve_srp
      MYSQL_USER: eve_srp
      MYSQL_PASSWORD: eve_srp
      MYSQL_DATABASE: eve_srp

  node:
    container_name: eve_srp_node
    image: node:12.19.0-alpine
    volumes: [".:/app"]
    working_dir: /app

  php-fpm:
    container_name: eve_srp_php-fpm
    build:
      context: config
      dockerfile: dockerfile-php74-fpm
    depends_on: [db]
    volumes: [".:/app"]
    working_dir: /app

  http:
    container_name: eve_srp_http
    image: nginx:1
    depends_on: [php-fpm]
    volumes: [".:/app", "./config/docker-nginx.conf:/etc/nginx/conf.d/default.conf"]
    ports: ["8000:80"]
